export const ROUTE_PATH = {
  NOT_FOUND: '/404',
  HOME: '/',
  DAPPS: '/dapps',
  COLLECTION: '/collection',
  INSCRIPTION: '/inscription',
  FAUCET: '/faucet',
  USE_TRUSTLESS: '/use-trustless-computer',
  WALLET: '/wallet',
  CONNECT_WALLET: '/connect-wallet',
  POOLS: '/pools',
  ADD_POOL: '/add-pool',
  SWAP: '/swap',
  MARKETS: '/markets',
  GET_STARTED: '/get-started',
  TOKEN: '/token',
  UPDATE_TOKEN_INFO: '/update-token-info',
  IDO: '/ido',
  IDO_MANAGE: '/ido/manage',
  TM_TRANSFER_HISTORY: '/tm-transfer-history',
  SWAP_HISTORY: '/swap-history',
  LAUNCHPAD: '/launchpad',
  LAUNCHPAD_MANAGE: '/launchpad/manage',
};
