import Layout from '@/layouts';
import Tokens from '@/modules/Tokens';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Trustless Markets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Tokens />
      </Layout>
    </>
  );
}
